### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by JunShine** [Quicksaver/Puzzle-Toolbars#68]
1.If I use a userChromeJS script：Switch Proxy。 in http://j.mozest.com/zh-CN/ucscript/script/30/, it can not work normally in the 2 version, but before version can work normally。
2.using the OmniSidebar and tree style tab extended, sometimes tabs will appear dislocation。
![default](https://cloud.githubusercontent.com/assets/10394308/5608359/99c3a44e-94bc-11e4-955a-89dd8582869f.png)

**Comment by Quicksaver** [comment]
1. It seems to be working fine for me. If you mean it doesn't show up in your toolbars, you have to drag the status bar into a toolbar in customize view. Even if you do this, does it still not work for you? If so, what exactly doesn't work?

2. This will be fixed in the next version, thanks for letting me know.
