### ISSUE TITLE
LastPass icon problem.

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/Puzzle-Toolbars#70]
It always seems that the LastPass icon gives your add-ons problems.  In the case of PT when I first start Fx the LP icon appears to the right of the download icon next to the search bar and then it moves over to PT in the location bar.

The LP icon has changed over the past few versions when it is displayed on the location bar.  It used to have the same look as other icons on the location bar, that is it had a gray hover color like the others.  Now it's a tall rectangular blue box when you hover over it.  I'm using the latest Fx version of LP btw.

**Comment by Quicksaver** [comment]
The icon appearance issue is easy to fix, it'll be in the next version, which I hope to upload later today.

As for it showing up in the navigation bar during startup, there's really nothing I can do there. LastPass forces its button to be added to the toolbar if, during startup, it doesn't find it anywhere in the window. And because LastPass initializes before PT, this will always be the case. The only way would be for LastPass to change its initialization routine in itself to not do that, and that I can't force on PT's side because, like I said, it initializes only afterwards.

But since it always moves to the location bar toolbar (or wherever) in a moment anyway, it's just a minor hiccup, I hope it's not something that will prevent you from using either add-on. :)
