### ISSUE TITLE
Stylish & Show Anchors 2 in location bar

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/Puzzle-Toolbars#71]
When Stylish toolbar button is moved to the location bar, it has about five pixels too much of padding/margin to the right of its image.

For [Show Anchors 2](https://addons.mozilla.org/en-US/firefox/addon/show-anchors-2/), when hovering it it doesn't have any styling applied to it. If not reproduced, try entering customize mode once then trying.

**Comment by Quicksaver** [comment]
Both easy to fix, thanks!

By the way, the issue with Show Anchors 2 is because of a mistake in its own code (even though I can fix it easily in PZT so it shouldn't happen anymore). I've already e-mailed the author about it, although I'm not sure it's still being maintained since the last released version was over a year ago.
