### ISSUE TITLE
Conflicts With OmniSidebar

### ISSUE THREAD

**Issue by Techy-Ben** [Quicksaver/Puzzle-Toolbars#79]
I have had trouble for a while in that often when I update Firefox or my add-ons, OmniSidebar will not work properly until I restart Firefox. I had no idea what was going on, but I think I know now. Puzzle-Toolbars is conflicting with OmniSidebar. When I update one of the two, the sidebar can no longer be opened. It completely dissapears, along with all traces of its openers. Sometimes it comes back automatically; sometimes I have to restart FF. However, after downloading the newest versions of OmniSidebar and Puzzle-Toolbars, the sidebar disappeared and did not return, even after restarting FF. I went through my list of add-ons and started disabling them, and when I got to Puzzle-Toolbars, the sidebar and its openers suddenly reappeared. I reenabled all the add-ons I had just disabled (most were still running because I had not restarted yet), and toggled the disable button for Puzzle-Toolbars. Sure enough, enabling PT removed the sidebar and disabling PT brought back the sidebar again.

**Comment by Quicksaver** [comment]
Could you try the latest Puzzle Toolbars v2.0.8 (https://addons.mozilla.org/firefox/addon/puzzle-toolbars/versions/) together with the latest beta of OmniSidebar v1.6b1 (https://addons.mozilla.org/firefox/addon/omnisidebar/versions/)?

I did fix some issues between the two in those versions, and I don't see these problems you mention locally, so hopefully those will work. Please let me know. By the way, you may have to restart your browser one last time after updating them (if the problem was on shutdown, your current versions may still not shutdown properly and cause problems with the new ones).

**Comment by Techy-Ben** [comment]
I downloaded the new versions and they work perfectly. Thanks!
