### ISSUE TITLE
Black background?

### ISSUE THREAD

**Issue by semool** [Quicksaver/Puzzle-Toolbars#81]
After the 2.1 update the Background of the Bar is totaly black

**Comment by Quicksaver** [comment]
That's not supposed to happen of course. Please try disabling all your other add-ons and going back to the default theme and let me know if it is still black then.

**Comment by semool** [comment]
Your right, it was my Theme. I changed it to another one and all is good again with Toolbar :)
Thank you

**Comment by Quicksaver** [comment]
Can you tell me which theme was causing it?

**Comment by semool** [comment]
https://addons.mozilla.org/de/firefox/addon/simple-stylish/
Its an very simple and old Theme.
Now im using this one and all works fine.
https://addons.mozilla.org/de/firefox/addon/lapiz-grey/

**Comment by Quicksaver** [comment]
Thanks for telling me! There was indeed a bug that prevented themes to apply properly to the corner bar. This should be fixed in the next version, but if you don't want to wait to keep using your previous theme, you can try beta version 2.1.1b1, you can find it at https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.1b1
