### ISSUE TITLE
Why did you remove Support for Firefox 38?

### ISSUE THREAD

**Issue by mkaply** [Quicksaver/Puzzle-Toolbars#84]
FYI, Firefox 38 is still being used for the Firefox ESR.

You shouldn't remove support for Firefox 38 until it is made EOL.

**Comment by Quicksaver** [comment]
True, and I do plan to keep support for ESR from now on, starting with the next ESR 45.

However, the updates since the last version compatible with Fx38 ([2.1.2](https://addons.mozilla.org/en-US/firefox/addon/puzzle-toolbars/versions/?page=1#version-2.1.2)) are fairly minor. If you're using the ESR you can just stick with that version for now and you're not really losing anything.

**Comment by mkaply** [comment]
Thanks! I appreciate that.
