### ISSUE TITLE
Button deformation for "Pick & Save Images"

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/Puzzle-Toolbars#88]
https://addons.mozilla.org/en-US/firefox/addon/picknsave/ 
STR: Move the toolbar button to "Location Bar Puzzle Bar".

"Move to Lateral Puzzle Bar" will also expand the width of the bar.

**Comment by Quicksaver** [comment]
Could you please try [beta version 2.1.13b1](https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.13b1) and see if the button displays as intended? If you could test in either of these systems (because I don't have access to any of them to test at the moment), I would really appreciate it as well: Windows 10, Linux, and Mac OSX.

**Comment by yfdyh000** [comment]
Looks it fixed the issue for "Location Bar Puzzle Bar" on Win10 & Linux. I don't have a Mac to test.
"Move to Lateral Puzzle Bar" are still expanding the width of the bar, but it may not be able to avoid.

**Comment by Quicksaver** [comment]
> "Move to Lateral Puzzle Bar" are still expanding the width of the bar, but it may not be able to avoid.

Right, I forgot to reply to that point, that's expected since the button has a dropmarker icon, which makes it larger than most other buttons that don't have one. All buttons like those will expand the toolbar. I once played with placing the dropmarkers below the main button in the lateral toolbar; it didn't work out very well. ;)
