### ISSUE TITLE
Video DownloadHelper icon left-click not working

### ISSUE THREAD

**Issue by bluefield1991** [Quicksaver/Puzzle-Toolbars#91]
Thank your for this add-on! 
The only problem I have so far is that if I move the Video DownloadHelper (https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/) icon into the location bar and restart the browser, left-click on the Video DownloadHelper icon won't popup its menu. The colour change and number notification of the icon still work, it's just the left-click doesn't work.
![capture](https://cloud.githubusercontent.com/assets/15224038/15565497/768ab5c6-235e-11e6-8fc8-c1b571dfdd5b.PNG)
(Regarding to my review on Mozilla https://addons.mozilla.org/en-US/firefox/addon/puzzle-toolbars/reviews/798092/)

**Comment by Quicksaver** [comment]
Unfortunately I can't fix this on my side because VDH's initialization methods are closed-off to other add-ons. I've already reported this to their support, hopefully they'll be able to fix it soon; you can follow it here: http://www.downloadhelper.net/support.php then find the topic "VDH button not initialized at startup if placed on dynamically created toolbar" (I couldn't find a way to give you a direct link, which is weird but oh well.)

**Comment by bluefield1991** [comment]
I see, thanks. (Wow, you're really efficient!)

**Comment by Quicksaver** [comment]
It seems to work now with the latest version of VDH at least, so I'm guessing they fixed it in the meantime. Please re-open if you still have any problems with it.
