### ISSUE TITLE
Flexible separators

### ISSUE THREAD

**Issue by SomeDude77** [Quicksaver/Puzzle-Toolbars#99]
I just installed this in Firefox 49. When this extension is enabled Flexible separators from "classic theme restorer" on the toolbars become squished and look like separators, they cannot be moved around or removed. And if any space or flexible space is placed on the right side of the search bar they will move the buttons on that side to the left and there's no way of moving them back in place until this extension is disabled. After which everything goes back to normal.

**Comment by Quicksaver** [comment]
They look just fine to me. What operating system are you on? Do you have CTR's latest version 1.5.8.1?

**Comment by SomeDude77** [comment]
I'm using windows 7 x64, and yes CTR 1.5.8.1.

**Comment by Quicksaver** [comment]
Have you tried removing and re-adding the separators? I don't see a reason for why you should need to, but maybe you added those separators in an older version of CTR that just aren't recognized properly anymore.

**Comment by SomeDude77** [comment]
Oops i mean flexible spaces, not separators. Regular spaces, and separators are added and removed without any problems, but the flexible spaces that were added before become squeezed and nonfunctional while on the toolbars, and no further flexible spaces can be added after this extension is installed.

I only install this for the horizontal spaces on the hamburger menu, I disable all other functions. Any way of adding horizontal spaces to the hamburger menu via userChrome instead of installing this extension?

**Comment by Quicksaver** [comment]
> the flexible spaces that were added before become squeezed and nonfunctional while on the toolbars, and no further flexible spaces can be added after this extension is installed.

That's weird. With Puzzle Toolbars enabled, the flexible spaces available are the ones included in Puzzle Toolbars itself, you should at least be able to add and remove them without a problem. What Firefox version are you using?

If you disable all your other add-ons except for Puzzle Toolbars, do they work then?

**Comment by SomeDude77** [comment]
I'm using the latest v49.0.2 and yea I just tried disabling all addons but Puzzle bars and the problem still exists. Anyway I made due with regular spaces instead, much less hassle even if flexible spaces worked.

**Comment by Quicksaver** [comment]
Hmm, if you disable Puzzle Toolbars (and restart Firefox just to make sure), can you remove those flexible spaces you have?

**Comment by SomeDude77** [comment]
Yeah if i disable puzzle toolbars everything goes back to normal and i can remove and add mor flexible spaces.

**Comment by Quicksaver** [comment]
Alright, please do a final test for me. Disable Puzzle Toolbars and remove all of those flexible spaces you have. Then enable Puzzle Toolbars and try adding flexible spaces again with it already enabled. Does that work at all?.

(By the way, I'm sorry about having asked for your Firefox version, I realize you had already mentioned it, I must have completely missed it for some reason.)

**Comment by SomeDude77** [comment]
Yah I already tried that, didn't work. As soon as Puzzle bars is re-enabled the flexible separators become squished again, cannot be removed or added.

Here is the flexible space before and after I enabled puzzle toolbars.

![before](https://cloud.githubusercontent.com/assets/23091893/19802665/1b8bad1c-9d05-11e6-8b06-68f275fb1354.jpg)

![after](https://cloud.githubusercontent.com/assets/23091893/19802670/2131a956-9d05-11e6-8ea8-ec2328e4dfff.jpg)

**Comment by Quicksaver** [comment]
Ok, now I understand. I was not expecting you to try to add flexible spaces to the main toolbar. I was thinking only in other toolbars like the ones added by Puzzle Toolbars. I'm sorry it took me this long to catch up.

Unfortunately flexible spaces won't work there at all. You'll notice that if you disable Puzzle Toolbars and add a flexible space there, then exit customize mode, it's going to collapse anyway, only normal spaces appear. That's because the location bar itself acts as a much stronger flexible space (400x stronger in fact), in that it pushes everything else to its limits, including normal flexible spaces (1x strong). So unless you add 400 of those, it's not going to make a difference.

So Puzzle Toolbars just doesn't allow you to add any in there (or to the menu panel, because they would just look wrong in there anyway); it won't let you remove them either because it thinks it's not possible to have one there to be removed.

This is all expected. You're much better of adding normal spaces in there.
